project:
  type: website
  output-dir: C:/Users/btessema.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "My E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "images/BTessema_Resume_E-Portfolio.pdf"
        text: Resume
      - text: MGEM Projects
        menu:
          - href: gis.qmd
            text: GIS and Spatial Analysis
          - href: rsensing.qmd
            text: Remote Sensing
          - href: writing.qmd
            text: Writing & Research
      - href: capstone_project.qmd
        text: Capstone Project 
      - href: career.qmd
        text: Career Highlights      
      
        
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

