project:
  type: website
  output-dir: C:/Users/btessema.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "Your E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: images/BTessema_Resume_E-Portfolio.pdf
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

