project:
  type: website
  output-dir: C:/Users/btessema.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "My E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Resume_HTML.qmd
        text: Resume
      - href: content.qmd
        text: Geospatial Projects
      - href: career.qmd
        text: Career Highlights
        menu:
          - resume.qmd
        

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual


