---
title: "Resume"
---

# Education

-   Masters of Geomatics in Environmental Management (MGEM) August 2024 - Present
    -   University of British Columbia, Vancouver BC
    -   Capstone Project: Monitoring Mangrove Restoration in Madagascar Using Sentinel-2 imagery
    
    

-   Bachelor of Environmental Studies (BES Honors) September 2017 - June 2021
    -   York University, Toronto ON
    -   Specialization: Urban and Regional Environment
    -   Capstone Project: Certificate in Geographic Information Systems (GIS) and Remote Sensing


# Publications

*Peer-reviewed publications:*

-   List any peer-reviewed publications here.

*Reports:*

-   List any non-peer reviewed materials you'd like to share here.

# Conferences & Talks

*Invited Talks*

-   If you've been invited to speak in a professional setting, list that here.

*Conference Presentations*

-   If the presentation was at a conference, list them here.

# Awards & Honors

-   List any scholarships, bursaries, etc.

# Teaching Assistantships

-   List any TA positions you may have held.

# Institutional Service

-   Volunteering etc.
