---
title: "Research and Writing"
format: html
editor: visual
---

MGEM wasn’t just about data analysis and programming, it also challenged me to think critically about environmental decision-making and policy. This page highlights the non-technical side of my graduate work, where delved into diverse knowledge systems, policy analysis, and professional communication. Many of these projects were done alongside students from other master’s programs in the Faculty of Forestry, allowing us to exchange ideas and learn from each other’s diverse perspectives.

------------------------------------------------------------------------

### **Audience Analysis and Targeted Communication Strategies**

Communication is an essential skill that I always strive to improve in both professional and personal settings. During my time in MGEM, I learned that being an effective communicator stems from understanding the audience and their unique perspectives and stories. This understanding was further reinforced through an **Audience Analysis assignment**, which aimed to apply the principles of audience analysis to a chosen case study—in this case, a town hall meeting on fire safety. Together with MGEM students we worked to identify and analyze different audience groups, evaluate their communication preferences and barriers, and propose communication strategies tailored to each group.

I led the research and analysis for the **Local Indigenous Nations – Tribal Leaders**, a target audience group with specific needs and concerns regarding wildfire prevention and post-disaster recovery. The analysis involved understanding the unique cultural, social, and technological factors influencing effective communication with this group. Here's a brief snippet of my analysis and proposed communication improvement.

A**udience Analysis of Local Indigenous Nations - Tribal Leaders**

-   *"Priorities of local Indigenous communities are building resiliency through obtaining adequate resources for wildfire prevention and post-disaster recovery, meaningful consultation prior to fuel reduction treatments on ancestral lands, and establishing supportive government to government relationships.*

-   *Preserving and practicing cultural practices on the land is also an essential value of this audience group. Indigenous leaders are a marginalized group who are often excluded from decision making, thus appealing to ethos may exacerbate feelings of distrust.*

-   *Effective communication with this group requires recognizing the experience and authority of local tribal leaders, while being sensitive to their emotional and cultural history with the land. Potential barriers include limited access to adequate technological infrastructure, including high speed internet, especially for those living in rural and remote communities. Active participation, engagement can be difficult in virtual settings."*

**Proposed Improvements to Communication:**

-   *"The most important aspect in collaborating with Indigenous nations is building trust, through transparency, open communication, active listening, and meaningful engagement. Involving Indigenous leaders as part of the management team can reinforce government to government relationships. Likewise, co-creating communication materials and strategies with these leaders may be a more effective appeal to ethos within Indigenous communities than colonial government officials. In terms of language and delivery, recognition of Indigenous stewardship as complementary to western fire management regimes is crucial."*

**Reflection:**

This assignment was a valuable exercise in understanding the importance of tailoring communication strategies to meet the needs of diverse and marginalized groups. Leading the research for the **Indigenous audience** helped me appreciate the intricacies of cultural sensitivity and the significance of trust in communication. It also deepened my understanding of how traditional communication methods, such as top-down approaches, may be ineffective when engaging with historically excluded groups. I also learned how to propose communication strategies that were inclusive, respectful, and designed to address potential barriers.

```{r leaflet, include = FALSE}
library(dplyr); library(leaflet)

m <- leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addScaleBar(position = c("bottomleft")) %>%
  setView(-123.1207, 49.2827, zoom = 11)

```

------------------------------------------------------------------------

### Decolonial Model of Environmental Management

Another crucial component in my MGEM experience is the **Diverse Knowledge Systems in Sustainable Natural Resources Management** course, which focuses on recognizing different forms of knowledge and the factors influencing knowledge production, transmission, and ethical practices in resource management. The **Decolonial Model** of Environmental Management by [Artelle et al., 2021](https://www.tandfonline.com/doi/full/10.1080/21550085.2021.2002624), was a topic that stuck out to me as I collaborated on a discussion paper on this model with students from the Master of International Forestry (MIF), and Masters of Sustainable Forest Management (MSFM). We discussed Tenet V "Practices Reflect Local Values/Worldviews" from both a disciplinary and generalist perspective, reflect on our learning, and propose ways to incorporate these insights into their future careers. Below is a snippet from my MGEM perspective.

**My MGEM Perspective:**

*"As an MGEM student and aspiring geomatics professional, this tenet provides a crucial aspect of decolonizing the work we do and the services that we provide. Many geomatics and GIS technologies are built on Western science principles with a western worldview. Mapping is one example of how this field directly imposes western ideals on the interpretation and representation of a location or area, often propagating colonial and settler approaches into the results. This tenet has got me thinking about how the process of map making, particularly of indigenous territories or lands, can be deconstructed to involve decisions from indigenous leadership and ways of knowing that are tailored to and support local needs. Artelle et al., discussion of grizzly bear management led by local governance structure and legal systems highlights the successes that come from bringing neighbouring communities together and promoting continuing leadership and collaboration in conservation. Activities such as collaborative mapping, where Indigenous leaders are engaged in the mapping process can ensure it reflects Indigenous knowledge and priorities. Investing in training and capacity-building initiatives for Indigenous communities is another aspect in which a barrier can be reduced, fostering self-reliance."*

**Reflection:**\
This work was a valuable exercise in recognizing the role of Indigenous governance systems in environmental management and conservation. It reinforced the importance of considering diverse knowledge systems and practices when working in natural resource management. From my perspective as a geomatics student, it highlighted how crucial it is to decolonize the tools we use and ensure they are culturally relevant and inclusive of Indigenous ways of knowing. By adapting GIS and geomatics practices to support local governance and Indigenous perspectives, I can help contribute to more equitable and respectful environmental management in my future career. Working alongside colleagues from the Masters of International Forestry (MIF) allowed me to see the broader implications of this Tenet in policy and legal frameworks. I gained insight into the legal aspects of community governance and land rights opened my eyes to the importance of integrating Indigenous legal systems into national and international policies.

------------------------------------------------------------------------
